-- AlterEnum
ALTER TYPE "AuctionStatus" ADD VALUE IF NOT EXISTS 'CANCEL_PENDING';

-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bannedIp" TEXT;

ALTER TABLE "Auction" ADD COLUMN IF NOT EXISTS "cancelRequestedAt" TIMESTAMP(3);

ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "auctionId" INTEGER;
ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "previousAuctionStatus" TEXT;
ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "disputeAction" TEXT;
ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "adminNote" TEXT;
