ALTER TABLE "Auction" ADD COLUMN IF NOT EXISTS "quality" INTEGER;
ALTER TABLE "Auction" ADD COLUMN IF NOT EXISTS "lampLines" JSONB;

ALTER TABLE "MarketHistory" ADD COLUMN IF NOT EXISTS "quality" INTEGER;
ALTER TABLE "MarketHistory" ADD COLUMN IF NOT EXISTS "lampLines" JSONB;
