ALTER TABLE "ChatRoom"
ADD COLUMN IF NOT EXISTS "sellerConfirmed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "buyerConfirmed" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "User"
ALTER COLUMN "reputationScore" SET DEFAULT 0;

ALTER TYPE "AuctionStatus" ADD VALUE IF NOT EXISTS 'DISPUTED';
